### ISSUE TITLE
BUG: Error on Ruby 2.4.3 and Rails 5.0.2

### ISSUE THREAD

**Issue by ggrocco** [skylightio/skylight-ruby#114]
The extension Class [action_view.rb](https://github.com/skylightio/skylight-ruby/blob/master/skylight-core/lib/skylight/core/probes/action_view.rb) is failing on detect if the Rails is 5, 4 or 3... On this method `if method(:find_layout).arity == 3` is returning false.

**Comment by wagenet** [comment]
Can you send a full backtrace?

**Comment by ggrocco** [comment]
```
ArgumentError: wrong number of arguments (given 2, expected 3)
  from action_view/renderer/template_renderer.rb:75:in `find_layout'
  from spree_multi_domain/engine.rb:34:in `find_layout'
  from skylight/probes/action_view.rb:26:in `render_with_layout'
  from action_view/renderer/template_renderer.rb:52:in `render_template'
  from action_view/renderer/template_renderer.rb:14:in `render'
  from action_view/renderer/renderer.rb:42:in `render_template'
  from action_view/renderer/renderer.rb:23:in `render'
  from action_view/rendering.rb:104:in `_render_template'
  from action_controller/metal/streaming.rb:217:in `_render_template'
  from action_view/rendering.rb:83:in `render_to_body'
  from action_controller/metal/rendering.rb:52:in `render_to_body'
  from action_controller/metal/renderers.rb:142:in `render_to_body'
  from abstract_controller/rendering.rb:26:in `render'
  from action_controller/metal/rendering.rb:36:in `render'
  from action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  from active_support/core_ext/benchmark.rb:12:in `block in ms'
  from benchmark.rb:308:in `realtime'
  from active_support/core_ext/benchmark.rb:12:in `ms'
  from action_controller/metal/instrumentation.rb:44:in `block in render'
  from action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  from active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  from action_controller/metal/instrumentation.rb:43:in `render'
  from wicked_pdf/pdf_helper.rb:42:in `render_with_wicked_pdf'
  from wicked_pdf/pdf_helper.rb:27:in `render'
  from action_controller/metal/implicit_render.rb:36:in `default_render'
  from action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
  from action_controller/metal/basic_implicit_render.rb:4:in `tap'
  from action_controller/metal/basic_implicit_render.rb:4:in `send_action'
  from abstract_controller/base.rb:188:in `process_action'
  from action_controller/metal/rendering.rb:30:in `process_action'
  from abstract_controller/callbacks.rb:20:in `block in process_action'
  from active_support/callbacks.rb:126:in `call'
  from active_support/callbacks.rb:506:in `block (2 levels) in compile'
  from active_support/callbacks.rb:455:in `call'
  from active_support/callbacks.rb:448:in `block (2 levels) in around'
  from active_support/callbacks.rb:286:in `block (2 levels) in halting'
  from audited/sweeper.rb:14:in `around'
  from active_support/callbacks.rb:405:in `public_send'
  from active_support/callbacks.rb:405:in `block in make_lambda'
  from active_support/callbacks.rb:285:in `block in halting'
  from active_support/callbacks.rb:447:in `block in around'
  from active_support/callbacks.rb:455:in `call'
  from active_support/callbacks.rb:448:in `block (2 levels) in around'
  from active_support/callbacks.rb:286:in `block (2 levels) in halting'
  from audited/sweeper.rb:14:in `around'
  from active_support/callbacks.rb:405:in `public_send'
  from active_support/callbacks.rb:405:in `block in make_lambda'
  from active_support/callbacks.rb:285:in `block in halting'
  from active_support/callbacks.rb:447:in `block in around'
  from active_support/callbacks.rb:455:in `call'
  from active_support/callbacks.rb:101:in `__run_callbacks__'
  from active_support/callbacks.rb:750:in `_run_process_action_callbacks'
  from active_support/callbacks.rb:90:in `run_callbacks'
  from abstract_controller/callbacks.rb:19:in `process_action'
  from action_controller/metal/rescue.rb:20:in `process_action'
  from action_controller/metal/instrumentation.rb:32:in `block in process_action'
  from active_support/notifications.rb:164:in `block in instrument'
  from active_support/notifications/instrumenter.rb:21:in `instrument'
  from active_support/notifications.rb:164:in `instrument'
  from action_controller/metal/instrumentation.rb:30:in `process_action'
  from action_controller/metal/params_wrapper.rb:248:in `process_action'
  from active_record/railties/controller_runtime.rb:18:in `process_action'
  from abstract_controller/base.rb:126:in `process'
  from action_view/rendering.rb:30:in `process'
  from action_controller/metal.rb:190:in `dispatch'
  from action_controller/metal.rb:262:in `dispatch'
  from action_dispatch/routing/route_set.rb:50:in `dispatch'
  from action_dispatch/routing/route_set.rb:32:in `serve'
  from action_dispatch/journey/router.rb:39:in `block in serve'
  from action_dispatch/journey/router.rb:26:in `each'
  from action_dispatch/journey/router.rb:26:in `serve'
  from action_dispatch/routing/route_set.rb:727:in `call'
  from rails/engine.rb:522:in `call'
  from rails/railtie.rb:193:in `public_send'
  from rails/railtie.rb:193:in `method_missing'
  from action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
  from action_dispatch/routing/mapper.rb:46:in `serve'
  from action_dispatch/journey/router.rb:39:in `block in serve'
  from action_dispatch/journey/router.rb:26:in `each'
  from action_dispatch/journey/router.rb:26:in `serve'
  from action_dispatch/routing/route_set.rb:727:in `call'
  from versioncake/rack/middleware.rb:17:in `call'
  from skylight/probes/middleware.rb:33:in `call'
  from warden/manager.rb:36:in `block in call'
  from warden/manager.rb:35:in `catch'
  from warden/manager.rb:35:in `call'
  from skylight/probes/middleware.rb:33:in `call'
  from rack/etag.rb:25:in `call'
  from skylight/probes/middleware.rb:33:in `call'
  from rack/conditional_get.rb:25:in `call'
  from skylight/probes/middleware.rb:33:in `call'
  from rack/head.rb:12:in `call'
  from skylight/probes/middleware.rb:33:in `call'
  from rack/session/abstract/id.rb:232:in `context'
  from rack/session/abstract/id.rb:226:in `call'
  from skylight/probes/middleware.rb:33:in `call'
  from action_dispatch/middleware/cookies.rb:613:in `call'
  from skylight/probes/middleware.rb:33:in `call'
  from action_dispatch/middleware/callbacks.rb:38:in `block in call'
  from active_support/callbacks.rb:97:in `__run_callbacks__'
  from active_support/callbacks.rb:750:in `_run_call_callbacks'
  from active_support/callbacks.rb:90:in `run_callbacks'
  from action_dispatch/middleware/callbacks.rb:36:in `call'
  from skylight/probes/middleware.rb:33:in `call'
  from action_dispatch/middleware/remote_ip.rb:79:in `call'
  from skylight/probes/middleware.rb:33:in `call'
  from action_dispatch/middleware/debug_exceptions.rb:49:in `call'
  from skylight/probes/middleware.rb:33:in `call'
  from action_dispatch/middleware/show_exceptions.rb:31:in `call'
  from skylight/probes/middleware.rb:33:in `call'
  from rails/rack/logger.rb:36:in `call_app'
  from rails/rack/logger.rb:24:in `block in call'
  from active_support/tagged_logging.rb:69:in `block in tagged'
  from active_support/tagged_logging.rb:26:in `tagged'
  from active_support/tagged_logging.rb:69:in `tagged'
  from rails/rack/logger.rb:24:in `call'
  from skylight/probes/middleware.rb:33:in `call'
  from action_dispatch/middleware/request_id.rb:24:in `call'
  from skylight/probes/middleware.rb:33:in `call'
  from rack/method_override.rb:22:in `call'
  from skylight/probes/middleware.rb:33:in `call'
  from rack/runtime.rb:22:in `call'
  from skylight/probes/middleware.rb:33:in `call'
  from action_dispatch/middleware/executor.rb:12:in `call'
  from skylight/probes/middleware.rb:33:in `call'
  from action_dispatch/middleware/static.rb:136:in `call'
  from skylight/probes/middleware.rb:33:in `call'
  from rack/sendfile.rb:111:in `call'
  from skylight/probes/middleware.rb:33:in `call'
  from raven/integrations/rack.rb:50:in `call'
  from skylight/probes/middleware.rb:33:in `call'
  from skylight/middleware.rb:79:in `call'
  from rails/engine.rb:522:in `call'
  from puma/configuration.rb:224:in `call'
  from puma/server.rb:600:in `handle_request'
  from puma/server.rb:435:in `process_client'
  from puma/server.rb:299:in `block in run'
  from puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by wagenet** [comment]
Looking at the error, the last items aren't Skylight. Does this problem go away when you aren't using Skylight?

**Comment by wagenet** [comment]
I'm going to keep looking, though. What version of Spree are you using?

**Comment by wagenet** [comment]
Looks like the issue is due to a bad interaction with https://github.com/spree-contrib/spree-multi-domain/blob/master/lib/spree_multi_domain/engine.rb which overwrites `find_layout`. I'm not sure if this is something we should fix or they should be fixing.

**Comment by wagenet** [comment]
IMO, spree_multi_domain shouldn't be changing function signatures. Instead the should have two separate method definitions, one for Rails 5+ and one for earlier versions. I think their solution is incorrect and you may find your best option is to fork and fix in that gem.

**Comment by ggrocco** [comment]
Yes, when I remove the skylight, we don't have problems! And if I the change the from:
```
# current version
if method(:find_layout).arity == 3
  # Rails 5
  layout = find_layout(path, locals.keys, [formats.first])
else
  # Rails 4
  layout = find_layout(path, locals.keys)
end
```
To:
```
# compare based on rails version
if Rails.gem_version >= Gem::Version.new('5.x')
  layout = find_layout(path, locals.keys, [formats.first])
else
  layout = find_layout(path, locals.keys)
end
```
Works for us!

**Comment by wagenet** [comment]
Yes, that change should work on our end, it just seems a bit sketchy for spree_multi_domain to be changing the arity of methods they didn't originally define. :/

**Comment by ggrocco** [comment]
@wagenet me too! They are changing a Rails definition, but check using Gem version is better anyway... don't you think?

**Comment by wagenet** [comment]
@ggrocco the fix is in master and in maint/1.5.x

**Comment by wagenet** [comment]
Thanks!

**Comment by Zeko369** [comment]
Having similar problems with Rails 6.0.0.beta3
`undefined method `keys' for #<Proc:0x00007fe26c593638>`

in the locals.keys on the same function call `layout = find_layout(path, locals.keys, [formats.first])`

**Comment by zvkemp** [comment]
Hi @Zeko369 - Can you try updating to [skylight-4.0.0.beta2](https://rubygems.org/gems/skylight/versions/4.0.0.beta2)?

**Comment by Zeko369** [comment]
Works perfectly, tnx.
Sorry for the late replay
