### ISSUE TITLE
[BUG] wrong number of arguments (given 1, expected 0) 

### ISSUE THREAD

**Issue by ggrocco** [skylightio/skylight-ruby#135]
Error on the 4.0.0.beta2 with sidekiq.
```
ArgumentError: wrong number of arguments (given 1, expected 0)
  from sidekiq/middleware/chain.rb:126:in `block in invoke'
  from skylight/core/instrumentable.rb:104:in `block in trace'
  from skylight/core/instrumenter.rb:126:in `trace'
  from skylight/core/instrumentable.rb:104:in `trace'
  from sidekiq/skylight/server_middleware.rb:11:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
  from skylight/core/sidekiq.rb:27:in `block in call'
  from skylight/core/instrumenter.rb:142:in `trace'
  from skylight/core/sidekiq.rb:25:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
  from sidekiq/middleware/chain.rb:133:in `invoke'
  from sidekiq/processor.rb:166:in `block in process'
  from sidekiq/processor.rb:137:in `block (6 levels) in dispatch'
  from sidekiq/job_retry.rb:108:in `local'
  from sidekiq/processor.rb:136:in `block (5 levels) in dispatch'
  from sidekiq.rb:36:in `block in <module:Sidekiq>'
  from sidekiq/processor.rb:132:in `block (4 levels) in dispatch'
  from sidekiq/processor.rb:243:in `stats'
  from sidekiq/processor.rb:127:in `block (3 levels) in dispatch'
  from sidekiq/job_logger.rb:8:in `call'
  from sidekiq/processor.rb:126:in `block (2 levels) in dispatch'
  from sidekiq/job_retry.rb:73:in `global'
  from sidekiq/processor.rb:125:in `block in dispatch'
  from sidekiq/logging.rb:48:in `with_context'
  from sidekiq/logging.rb:42:in `with_job_hash_context'
  from sidekiq/processor.rb:124:in `dispatch'
  from sidekiq/processor.rb:165:in `process'
  from sidekiq/processor.rb:83:in `process_one'
  from sidekiq/processor.rb:71:in `run'
  from sidekiq/util.rb:16:in `watchdog'
  from sidekiq/util.rb:25:in `block in safe_thread'
```

**Comment by zvkemp** [comment]
Thank you for the report, @ggrocco. Can you please let me know what version of Sidekiq you are running?

**Comment by ggrocco** [comment]
@zvkemp I was running together with this gem: https://github.com/lintci/sidekiq-skylight, after removing stop the error and start to work normally. I believe this can be closed.

**Comment by zvkemp** [comment]
Ok, thank you for letting us know. For anyone who may land on this issue in the future, we have documented this incompatibility [here](https://www.skylight.io/support/background-jobs#migrating-your-existing-background-jobs-setup).
