### ISSUE TITLE
Not using resque, causes zeitwerk panic (in rails app)

### ISSUE THREAD

**Issue by nayena** [skylightio/skylight-ruby#152]
I am using sidekiq as my background job tool, but there seems to be some requiring happening in the gem, that causes my application to crash. 

I have tested with multiple versions of the `skylight` gem, but it seems to be due to something in regards to the loading happening with zeitwerk. 

It only happens, when I run rails in production mode.

Below are the logs from the `5.0.0.beta` release:

```
LoadError: cannot load such file -- resque
/home/deploy/es-zonen/shared/bundle/ruby/2.7.0/gems/skylight-5.0.0.beta/lib/skylight/probes.rb:145:in `require'
/home/deploy/es-zonen/shared/bundle/ruby/2.7.0/gems/skylight-5.0.0.beta/lib/skylight/probes.rb:145:in `require'
/home/deploy/es-zonen/shared/bundle/ruby/2.7.0/gems/zeitwerk-2.3.1/lib/zeitwerk/kernel.rb:34:in `require'
/home/deploy/es-zonen/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
```

**Comment by nayena** [comment]
This happened due to a mistake in my upgrading of rails 5.2 to 6.0, setting some default that I didn't notice. Apologies for the issue. Will close it.
