### ISSUE TITLE
Ruby 2.2.0 - Skylight probes cause test failure

### ISSUE THREAD

**Issue by KieranP** [skylightio/skylight-ruby#25]
Running test suite after switching to Ruyb 2.2.0:

```
/Users/work/.rvm/gems/ruby-2.2.0/gems/skylight-0.6.0/lib/skylight/probes.rb:81:in `require': cannot load such file -- test/unit/assertions (LoadError)
	from /Users/work/.rvm/gems/ruby-2.2.0/gems/skylight-0.6.0/lib/skylight/probes.rb:81:in `require'
	from /Users/work/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
	from /Users/work/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /Users/work/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
	from /Users/work/.rvm/gems/ruby-2.2.0/gems/rspec-rails-2.14.2/lib/rspec/rails/adapters.rb:17:in `rescue in <module:Rails>'
	from /Users/work/.rvm/gems/ruby-2.2.0/gems/rspec-rails-2.14.2/lib/rspec/rails/adapters.rb:12:in `<module:Rails>'
	from /Users/work/.rvm/gems/ruby-2.2.0/gems/rspec-rails-2.14.2/lib/rspec/rails/adapters.rb:6:in `<module:RSpec>'
	from /Users/work/.rvm/gems/ruby-2.2.0/gems/rspec-rails-2.14.2/lib/rspec/rails/adapters.rb:5:in `<top (required)>'
	from /Users/work/.rvm/gems/ruby-2.2.0/gems/skylight-0.6.0/lib/skylight/probes.rb:81:in `require'
	from /Users/work/.rvm/gems/ruby-2.2.0/gems/skylight-0.6.0/lib/skylight/probes.rb:81:in `require'
	from /Users/work/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
	from /Users/work/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /Users/work/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
	from /Users/work/.rvm/gems/ruby-2.2.0/gems/rspec-rails-2.14.2/lib/rspec/rails.rb:11:in `<top (required)>'
	from /Users/work/.rvm/gems/ruby-2.2.0/gems/skylight-0.6.0/lib/skylight/probes.rb:81:in `require'
	from /Users/work/.rvm/gems/ruby-2.2.0/gems/skylight-0.6.0/lib/skylight/probes.rb:81:in `require'
	from /Users/work/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
	from /Users/work/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /Users/work/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
```

**Comment by wagenet** [comment]
@KieranP The reason you're seeing Skylight in the trace is because we hook into the require method to enable specific probes to be loaded at the correct time. In this case it just looks like the file `test/unit/assertions` is unavailable.

Have you verified that this issue is resolved when Skylight is not present?

**Comment by wagenet** [comment]
@KieranP did you figure it out?

**Comment by KieranP** [comment]
@wagenet Our upgrade of ruby from 2.1.0 to 2.2.0 is on hold for now, but I believe you were right in that it was just the hooks of skylight and the actual cause was our test files referring to the old test/unit/assertions path, and seems to be documented in various rails bug reports.

**Comment by mecampbellsoup** [comment]
Hey @wagenet @KieranP any more updates on this? Hit the same snag when bumping our Rails project's Ruby version from 1.9.3 to 2.2.3...

**Comment by wagenet** [comment]
@mecampbellsoup as I mentioned, I think you should ignore any references to `lib/skylight/probes.rb` in your backtrace. The only reason that file is showing up is because we're hooking into the require method. It's not impossible that we could be causing an issue, but I think it's pretty unlikely.
