### ISSUE TITLE
Setup never completes because of spring

### ISSUE THREAD

**Issue by hakunin** [skylightio/skylight-ruby#33]
I've let skylight setup run for over 20 minutes and it didn't complete, interrupting it yields this:

```
michal@10:06:11:~/dev/mozek (feature/add-skylight)$ skylight setup 0NSPO3CdGlqk
/Users/michal/.rvm/gems/ruby-2.2.1/gems/spring-1.3.4/lib/spring/client/run.rb:99:in `gets': Interrupt
	from /Users/michal/.rvm/gems/ruby-2.2.1/gems/spring-1.3.4/lib/spring/client/run.rb:99:in `verify_server_version'
	from /Users/michal/.rvm/gems/ruby-2.2.1/gems/spring-1.3.4/lib/spring/client/run.rb:56:in `run'
	from /Users/michal/.rvm/gems/ruby-2.2.1/gems/spring-1.3.4/lib/spring/client/run.rb:37:in `warm_run'
	from /Users/michal/.rvm/gems/ruby-2.2.1/gems/spring-1.3.4/lib/spring/client/run.rb:26:in `call'
	from /Users/michal/.rvm/gems/ruby-2.2.1/gems/spring-1.3.4/lib/spring/client/command.rb:7:in `call'
	from /Users/michal/.rvm/gems/ruby-2.2.1/gems/spring-1.3.4/lib/spring/client/rails.rb:24:in `call'
	from /Users/michal/.rvm/gems/ruby-2.2.1/gems/spring-1.3.4/lib/spring/client/command.rb:7:in `call'
	from /Users/michal/.rvm/gems/ruby-2.2.1/gems/spring-1.3.4/lib/spring/client.rb:26:in `run'
	from /Users/michal/.rvm/gems/ruby-2.2.1/gems/spring-1.3.4/bin/spring:48:in `<top (required)>'
	from /Users/michal/.rvm/gems/ruby-2.2.1/gems/spring-1.3.4/lib/spring/binstub.rb:11:in `load'
	from /Users/michal/.rvm/gems/ruby-2.2.1/gems/spring-1.3.4/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/michal/dev/mozek/bin/spring:16:in `require'
	from /Users/michal/dev/mozek/bin/spring:16:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

Removing spring from gemfile and stopping spring helped.

**Comment by carllerche** [comment]
Thanks for the report.

Currently, Skylight does not support being run with Spring (Spring has a number of other issues in general and will make debugging problems trickier). I will make a note to come back and revisit this in the future though.

Closing for now.

**Comment by hakunin** [comment]
Note that I wasn't running it with spring explicitly, it just got into spring somehow, since I use spring on development.

That should be avoided, or a helpful message should be raised, unless you want people to be just stuck like I was.
