### ISSUE TITLE
libskylight on Alpine based containers

### ISSUE THREAD

**Issue by rainerborene** [skylightio/skylight-ruby#35]
I don't know why `libskylight` does not work under Alpine Linux Distribution. I thought it was  statically compiled binary but seems to be dependent with some system library.

Here's my Dockerfile:
```Dockerfile
FROM alpine:edge

RUN echo 'gem: --no-rdoc --no-ri' > /etc/gemrc

ENV GEM_HOME /usr/local/bundle
ENV PATH $GEM_HOME/bin:$PATH
ENV BUNDLE_APP_CONFIG $GEM_HOME

RUN apk --update add \
      git \
      tzdata \
      build-base \
      nodejs \
      imagemagick \
      postgresql-dev \
      ruby-dev \
      ruby-bundler \
      ruby-nokogiri \
      ruby-mysql2 \
      ruby-raindrops && rm -rf /var/cache/apk/* && rm -rf /usr/share/ri/*

CMD ["/bin/sh"]
```

Error message:
```
/app # rails server
Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Ignoring bcrypt-3.1.9 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.9
/usr/local/bundle/gems/skylight-0.6.0/lib/skylight/native.rb:27:in `load_libskylight': [SKYLIGHT] dlerror; msg=Error relocating /usr/local/bundle/gems/skylight-0.6.0/lib/skylight/native/x86_64-linux/libskylight.so: __register_atfork: symbol not found (RuntimeError)
	from /usr/local/bundle/gems/skylight-0.6.0/lib/skylight/native.rb:27:in `<module:Skylight>'
	from /usr/local/bundle/gems/skylight-0.6.0/lib/skylight/native.rb:3:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
	from /usr/local/bundle/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `block in require'
	from /usr/local/bundle/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
	from /usr/local/bundle/gems/skylight-0.6.0/lib/skylight/core.rb:8:in `<module:Skylight>'
	from /usr/local/bundle/gems/skylight-0.6.0/lib/skylight/core.rb:3:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
	from /usr/local/bundle/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `block in require'
	from /usr/local/bundle/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
	from /usr/local/bundle/gems/skylight-0.6.0/lib/skylight.rb:1:in `<top (required)>'
	from /usr/local/bundle/gems/bundler-1.9.9/lib/bundler/runtime.rb:76:in `require'
	from /usr/local/bundle/gems/bundler-1.9.9/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /usr/local/bundle/gems/bundler-1.9.9/lib/bundler/runtime.rb:72:in `each'
	from /usr/local/bundle/gems/bundler-1.9.9/lib/bundler/runtime.rb:72:in `block in require'
	from /usr/local/bundle/gems/bundler-1.9.9/lib/bundler/runtime.rb:61:in `each'
	from /usr/local/bundle/gems/bundler-1.9.9/lib/bundler/runtime.rb:61:in `require'
	from /usr/local/bundle/gems/bundler-1.9.9/lib/bundler.rb:134:in `require'
	from /app/config/application.rb:8:in `<top (required)>'
	from /usr/local/bundle/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:79:in `require'
	from /usr/local/bundle/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:79:in `block in server'
	from /usr/local/bundle/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:76:in `tap'
	from /usr/local/bundle/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:76:in `server'
	from /usr/local/bundle/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /usr/local/bundle/gems/railties-4.1.7/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by rainerborene** [comment]
Just figured out that problem. Alpine Linux changed to musl recently and `libskylight` depends on glibc.
