### ISSUE TITLE
crash on instrument_method created by attr_writer

### ISSUE THREAD

**Issue by yltsrc** [skylightio/skylight-ruby#38]
```
class A
 attr_accessor :tmp
end

A.include(Skylight::Helpers)
A.instrument_method :tmp=
```

produces

```
/home/vagrant/.rvm/gems/ruby-2.1.6@rails_4.2/gems/skylight-0.6.1/lib/skylight/helpers.rb:101:in `class_eval': /home/vagrant/.rvm/gems/ruby-2.1.6@rails_4.2/gems/skylight-0.6.1/lib/skylight/helpers.rb:111: syntax error, unexpected &
              before_instrument_strict_validation=(*args, &blk)
                                                           ^ (SyntaxError)
	from /home/vagrant/.rvm/gems/ruby-2.1.6@rails_4.2/gems/skylight-0.6.1/lib/skylight/helpers.rb:101:in `__sk_instrument_method_on'
	from /home/vagrant/.rvm/gems/ruby-2.1.6@rails_4.2/gems/skylight-0.6.1/lib/skylight/helpers.rb:88:in `instrument_method'
```

**Comment by wagenet** [comment]
@yltsrc sorry for the slow response. I've verified that this is indeed an issue.

**Comment by wagenet** [comment]
@yltsrc Sorry for the slow follow-up here. I have an internal PR for this issue that should get merged soon and hopefully be in our next release.
