### ISSUE TITLE
undefined method `register' for Skylight::Probes:Module

### ISSUE THREAD

**Issue by lukelex** [skylightio/skylight-ruby#44]
I'm trying out the gem, `skylight (0.8.0.beta.1)`, under Grape and I keep getting this error, no matter what probe I require:

```
require 'grape'
require 'skylight/probes/grape'
```

```
/Users/u0157355/.rvm/gems/ruby-2.2.2@api-engine/gems/skylight-0.8.0.beta.1/lib/skylight/probes/redis.rb:28:in `<module:Probes>': undefined method `register' for Skylight::Probes:Module (NoMethodError)
	from /Users/u0157355/.rvm/gems/ruby-2.2.2@api-engine/gems/skylight-0.8.0.beta.1/lib/skylight/probes/redis.rb:2:in `<module:Skylight>'
	from /Users/u0157355/.rvm/gems/ruby-2.2.2@api-engine/gems/skylight-0.8.0.beta.1/lib/skylight/probes/redis.rb:1:in `<top (required)>'
	from /Users/u0157355/.rvm/gems/ruby-2.2.2@api-engine/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/u0157355/.rvm/gems/ruby-2.2.2@api-engine/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/u0157355/.rvm/gems/ruby-2.2.2@api-engine/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/u0157355/.rvm/gems/ruby-2.2.2@api-engine/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/u0157355/projects/codelogic/api-engine/api/engine/collection.rb:2:in `<top (required)>'
	from /Users/u0157355/projects/codelogic/api-engine/api/server.rb:7:in `require_relative'
	from /Users/u0157355/projects/codelogic/api-engine/api/server.rb:7:in `<top (required)>'
	from /Users/u0157355/.rvm/gems/ruby-2.2.2@api-engine/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/u0157355/.rvm/gems/ruby-2.2.2@api-engine/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/u0157355/.rvm/gems/ruby-2.2.2@api-engine/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/u0157355/.rvm/gems/ruby-2.2.2@api-engine/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/u0157355/projects/codelogic/api-engine/config.ru:3:in `block in <main>'
	from /Users/u0157355/.rvm/gems/ruby-2.2.2@api-engine/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/u0157355/.rvm/gems/ruby-2.2.2@api-engine/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from /Users/u0157355/projects/codelogic/api-engine/config.ru:in `new'
	from /Users/u0157355/projects/codelogic/api-engine/config.ru:in `<main>'
	from /Users/u0157355/.rvm/gems/ruby-2.2.2@api-engine/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /Users/u0157355/.rvm/gems/ruby-2.2.2@api-engine/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/u0157355/.rvm/gems/ruby-2.2.2@api-engine/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /Users/u0157355/.rvm/gems/ruby-2.2.2@api-engine/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /Users/u0157355/.rvm/gems/ruby-2.2.2@api-engine/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
	from /Users/u0157355/.rvm/gems/ruby-2.2.2@api-engine/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
	from /Users/u0157355/.rvm/gems/ruby-2.2.2@api-engine/gems/rack-1.6.4/lib/rack/server.rb:272:in `start'
	from /Users/u0157355/.rvm/gems/ruby-2.2.2@api-engine/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
	from /Users/u0157355/.rvm/gems/ruby-2.2.2@api-engine/gems/rack-1.6.4/bin/rackup:4:in `<top (required)>'
	from /Users/u0157355/.rvm/gems/ruby-2.2.2@api-engine/bin/rackup:23:in `load'
	from /Users/u0157355/.rvm/gems/ruby-2.2.2@api-engine/bin/rackup:23:in `<main>'
	from /Users/u0157355/.rvm/gems/ruby-2.2.2@api-engine/bin/ruby_executable_hooks:15:in `eval'
	from /Users/u0157355/.rvm/gems/ruby-2.2.2@api-engine/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by wagenet** [comment]
@lukelex I'm guessing you figured it out. If you're still having issues, shoot us an email: support@skylight.io.

**Comment by lukelex** [comment]
@wagenet Yes I did, but only after I got up for a cup of coffee. It was my mistake.

**Comment by wagenet** [comment]
@lukelex, no problem. Thanks for trying it out. By the way, there's a new beta out. Instructions up at docs.skylight.io/grape.
