### ISSUE TITLE
YAML.load_file causes error

### ISSUE THREAD

**Issue by kenaniah** [skylightio/skylight-ruby#56]
https://github.com/skylightio/skylight-ruby/blob/master/lib/skylight/user_config.rb#L25 throws an error when it encounters an empty yaml file at `~/.skylight`

```
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/skylight-0.10.0/lib/skylight/user_config.rb:26:in `reload': undefined method `[]' for false:FalseClass (NoMethodError)
    from /usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/skylight-0.10.0/lib/skylight/user_config.rb:13:in `initialize'
    from /usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/skylight-0.10.0/lib/skylight/user_config.rb:9:in `new'
    from /usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/skylight-0.10.0/lib/skylight/user_config.rb:9:in `instance'
    from /usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/skylight-0.10.0/lib/skylight/railtie.rb:36:in `block in <class:Railtie>'
    from /usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
    from /usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
    from /usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
```

This sometimes happens if a user uninstalls the skylight gem and reinstalls it.

**Comment by wagenet** [comment]
Thanks for the report. I'll look into this.

**Comment by kenaniah** [comment]
FYI, the error can be easily reproduced by truncating the `~/.skylight` file. With zero content, it is not a valid YAML file and the YAML parser returns false, which causes this error to propagate.

**Comment by wagenet** [comment]
Yup, it's a simple fix, just forgot that it returned `false` if it couldn't parse. Thanks again!

**Comment by wagenet** [comment]
Was fixed a while ago.
