### ISSUE TITLE
Skylight failed to connect causes unicorn to crash (KILL)

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [skylightio/skylight-ruby#60]
Hi and thanks for your great service!

We are a startup which are happily using Skylight, but we are currently facing an issue during our deploys. We use capistrano, right after deploy sometimes the unicorn process is stuck and kill itself, ending with a non-running server.

In our production.log, we found the following errors (from the most recent to the least one):

```
deployer@ip-xxx:~/apps/carbide/shared/log$ tac unicorn.log | grep skylight
ERROR:skylight::ipc::server: something unexpected happen with the connection; err=Error { repr: Custom(Custom { kind: Other, error: StringError("unexpected connection close") }) }
ERROR:skylight::ipc::server: something unexpected happen with the connection; err=Error { repr: Custom(Custom { kind: Other, error: StringError("unexpected connection close") }) }
ERROR:skylight::ipc::server: something unexpected happen with the connection; err=Error { repr: Custom(Custom { kind: Other, error: StringError("unexpected connection close") }) }
ERROR:skylight::ipc::server: something unexpected happen with the connection; err=Error { repr: Custom(Custom { kind: Other, error: StringError("unexpected connection close") }) }
ERROR:skylight::ipc::server: something unexpected happen with the connection; err=Error { repr: Custom(Custom { kind: Other, error: StringError("unexpected connection close") }) }
ERROR:skylight::ipc::server: something unexpected happen with the connection; err=Error { repr: Custom(Custom { kind: Other, error: StringError("unexpected connection close") }) }
ERROR:skylight::ipc::server: something unexpected happen with the connection; err=Error { repr: Custom(Custom { kind: Other, error: StringError("unexpected connection close") }) }
ERROR:skylight::ipc::server: something unexpected happen with the connection; err=Error { repr: Custom(Custom { kind: Other, error: StringError("unexpected connection close") }) }
ERROR:skylight::ipc::server: something unexpected happen with the connection; err=Error { repr: Custom(Custom { kind: Other, error: StringError("unexpected connection close") }) }
ERROR:skylight::ipc::server: something unexpected happen with the connection; err=Error { repr: Custom(Custom { kind: Other, error: StringError("unexpected connection close") }) }
ERROR:skylight::ipc::client: could not send message to daemon; err=ClientSendMessageFailure
ERROR:skylight::ipc::server: something unexpected happen with the connection; err=Error { repr: Custom(Custom { kind: Other, error: StringError("unexpected connection close") }) }
ERROR:skylight::ipc::server: something unexpected happen with the connection; err=Error { repr: Custom(Custom { kind: Other, error: StringError("unexpected connection close") }) }
ERROR:skylight::ipc::server: something unexpected happen with the connection; err=Error { repr: Custom(Custom { kind: Other, error: StringError("unexpected connection close") }) }
ERROR:skylight::ipc::server: something unexpected happen with the connection; err=Error { repr: Custom(Custom { kind: Other, error: StringError("unexpected connection close") }) }
/home/deployer/apps/carbide/shared/bundle/ruby/2.1.0/gems/skylight-0.10.2/lib/skylight/probes.rb:81:in `require'
/home/deployer/apps/carbide/shared/bundle/ruby/2.1.0/gems/skylight-0.10.2/lib/skylight/probes.rb:81:in `require'
/home/deployer/apps/carbide/shared/bundle/ruby/2.1.0/gems/skylight-0.10.2/lib/skylight/probes.rb:81:in `require'
/home/deployer/apps/carbide/shared/bundle/ruby/2.1.0/gems/skylight-0.10.2/lib/skylight/probes.rb:81:in `require'
/home/deployer/apps/carbide/shared/bundle/ruby/2.1.0/gems/skylight-0.10.2/lib/skylight/probes.rb:81:in `require'
/home/deployer/apps/carbide/shared/bundle/ruby/2.1.0/gems/skylight-0.10.2/lib/skylight/probes.rb:81:in `require'
/home/deployer/apps/carbide/shared/bundle/ruby/2.1.0/gems/skylight-0.10.2/lib/skylight/probes.rb:81:in `require'
/home/deployer/apps/carbide/shared/bundle/ruby/2.1.0/gems/skylight-0.10.2/lib/skylight/probes.rb:81:in `require'
/home/deployer/apps/carbide/shared/bundle/ruby/2.1.0/gems/skylight-0.10.2/lib/skylight/probes.rb:81:in `require'
/home/deployer/apps/carbide/shared/bundle/ruby/2.1.0/gems/skylight-0.10.2/lib/skylight/probes.rb:81:in `require'
/home/deployer/apps/carbide/shared/bundle/ruby/2.1.0/gems/skylight-0.10.2/lib/skylight/probes.rb:81:in `require'
/home/deployer/apps/carbide/shared/bundle/ruby/2.1.0/gems/skylight-0.10.2/lib/skylight/probes.rb:81:in `require'
/home/deployer/apps/carbide/shared/bundle/ruby/2.1.0/gems/skylight-0.10.2/lib/skylight/probes.rb:81:in `require'
/home/deployer/apps/carbide/shared/bundle/ruby/2.1.0/gems/skylight-0.10.2/lib/skylight/probes.rb:81:in `require'
/home/deployer/apps/carbide/shared/bundle/ruby/2.1.0/gems/skylight-0.10.2/lib/skylight/probes.rb:81:in `require'
/home/deployer/apps/carbide/shared/bundle/ruby/2.1.0/gems/skylight-0.10.2/lib/skylight/probes.rb:81:in `require'
/home/deployer/apps/carbide/shared/bundle/ruby/2.1.0/gems/skylight-0.10.2/lib/skylight/probes.rb:81:in `require'
/home/deployer/apps/carbide/shared/bundle/ruby/2.1.0/gems/skylight-0.10.2/lib/skylight/probes.rb:81:in `require'
/home/deployer/apps/carbide/shared/bundle/ruby/2.1.0/gems/skylight-0.10.2/lib/skylight/probes.rb:81:in `require'
/home/deployer/apps/carbide/shared/bundle/ruby/2.1.0/gems/skylight-0.10.2/lib/skylight/probes.rb:81:in `require'
ERROR:skylight::ipc::server: something unexpected happen with the connection; err=Error { repr: Custom(Custom { kind: Other, error: StringError("unexpected connection close") }) }
ERROR:skylight::ipc::server: something unexpected happen with the connection; err=Error { repr: Custom(Custom { kind: Other, error: StringError("unexpected connection close") }) }
ERROR:skylight::ipc::server: something unexpected happen with the connection; err=Error { repr: Custom(Custom { kind: Other, error: StringError("unexpected connection close") }) }
ERROR:skylight::ipc::server: something unexpected happen with the connection; err=Error { repr: Custom(Custom { kind: Other, error: StringError("unexpected connection close") }) }
ERROR:skylight::ipc::server: something unexpected happen with the connection; err=Error { repr: Custom(Custom { kind: Other, error: StringError("unexpected connection close") }) }
ERROR:skylight::ipc::client: could not send message to daemon; err=ClientSendMessageFailure
ERROR:skylight::ipc::server: something unexpected happen with the connection; err=Error { repr: Custom(Custom { kind: Other, error: StringError("unexpected connection close") }) }
ERROR:skylight::ipc::server: something unexpected happen with the connection; err=Error { repr: Custom(Custom { kind: Other, error: StringError("unexpected connection close") }) }
ERROR:skylight::ipc::server: something unexpected happen with the connection; err=Error { repr: Custom(Custom { kind: Other, error: StringError("unexpected connection close") }) }
ERROR:skylight::cli: skylightd exiting abnormally; err=DaemonLockFailed
ERROR:skylight::ipc::server: something unexpected happen with the connection; err=Error { repr: Custom(Custom { kind: Other, error: StringError("unexpected connection close") }) }
```

And as you can see here, unicorn died:

```
E, [2016-03-21T20:51:02.912210 #25116] ERROR -- : worker=7 PID:30126 timeout (121s > 120s), killing
E, [2016-03-21T20:51:02.969624 #25116] ERROR -- : reaped #<Process::Status: pid 30126 SIGKILL (signal 9)> worker=7
```

Would like a few directions. We don't do anything beside including the skylight gem in our Rails 4.1, Ruby 2.1.2 and our skylight.yml is as simple as

``` yml

---
# The authentication token for the application.
authentication: <%= CONFIG[:skylight_authentication] %>
```

Any direction? Should I contact support team or keep the issue here to support other developers facing same issue?

**Comment by wagenet** [comment]
Hi @Fire-Dragon-DoL sorry for the trouble here! Nothing wrong with filing this issue, but can you also send us an email at support@skylight.io (or use the in-app messenger in Skylight)? That will help us prioritize your issue.

**Comment by wagenet** [comment]
Let me know if this is still an issue.

**Comment by Fire-Dragon-DoL** [comment]
Hey, sorry I forgot to close this. It stopped happening after a version update, whatever happened I assume it's fixed. Thanks

**Comment by wagenet** [comment]
Glad to hear it!
