### ISSUE TITLE
Probes issue in Rails 5

### ISSUE THREAD

**Issue by olivierlacan** [skylightio/skylight-ruby#63]
I understand Rails 5 isn't out yet, so this isn't a pressing issue but I thought you'd like to know that there seems to be an incompatibility in 0.10.2 (and 1.0.0.beta.4) with Probes and `action_cable/process/logging`:

```
=> Booting Puma
=> Rails 5.0.0.beta4 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
W, [2016-05-04T01:16:42.289959 #3584]  WARN -- : [SKYLIGHT] [1.0.0-beta4] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
Exiting
/Users/olivierlacan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/skylight-1.0.0.beta4/lib/skylight/probes.rb:81:in `require': cannot load such file -- action_cable/process/logging (LoadError)
	from /Users/olivierlacan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/skylight-1.0.0.beta4/lib/skylight/probes.rb:81:in `require'
	from /Users/olivierlacan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta4/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/olivierlacan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta4/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/olivierlacan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta4/lib/active_support/dependencies.rb:293:in `require'
	from /Users/olivierlacan/Development/perso/orientation/config.ru:8:in `block in <main>'
	from /Users/olivierlacan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/olivierlacan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:55:in `initialize'
	from /Users/olivierlacan/Development/perso/orientation/config.ru:in `new'
	from /Users/olivierlacan/Development/perso/orientation/config.ru:in `<main>'
	from /Users/olivierlacan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:49:in `eval'
	from /Users/olivierlacan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/olivierlacan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:40:in `parse_file'
	from /Users/olivierlacan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:318:in `build_app_and_options_from_config'
	from /Users/olivierlacan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:218:in `app'
	from /Users/olivierlacan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta4/lib/rails/commands/server.rb:59:in `app'
	from /Users/olivierlacan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:353:in `wrapped_app'
	from /Users/olivierlacan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta4/lib/rails/commands/server.rb:124:in `log_to_stdout'
	from /Users/olivierlacan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta4/lib/rails/commands/server.rb:77:in `start'
	from /Users/olivierlacan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta4/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	from /Users/olivierlacan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta4/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /Users/olivierlacan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta4/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /Users/olivierlacan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta4/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/olivierlacan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta4/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

Gemfile as follows: https://github.com/orientation/orientation/blob/84ee43b60eb079d9d23cfa7116a5fdd19b4e8529/Gemfile

For specifics you can see this rails-5 branch of Orientation: https://github.com/orientation/orientation/tree/rails-5

**Comment by olivierlacan** [comment]
Seems like the solution was simply to delete `require 'action_cable/process/logging'` from `config.ru` since it's been removed between betas. My bad.

Source: https://github.com/rails/rails/issues/23367#issuecomment-177352592
